stages:
  - develop
  - test
  - master
  - demo
  - demorun

prd_develop:
  stage: develop
  tags:
    - frontdevelop
  only:
    - develop
  script:
    - rm -rf /data/build/$CI_COMMIT_REF_NAME/$CI_PROJECT_NAME/src
    - rm -rf /data/build/$CI_COMMIT_REF_NAME/$CI_PROJECT_NAME/static
    - cp -rf ./. /data/build/$CI_COMMIT_REF_NAME/$CI_PROJECT_NAME/
    - cd /data/build/$CI_COMMIT_REF_NAME/$CI_PROJECT_NAME
    # - npm install
    - npm run develop
    - ls -a

prd_test:
  stage: test
  tags:
    - fronttest
  only:
    - test
  script:
    - rm -rf /data/build/$CI_COMMIT_REF_NAME/$CI_PROJECT_NAME/src
    - rm -rf /data/build/$CI_COMMIT_REF_NAME/$CI_PROJECT_NAME/static
    - cp -rf ./. /data/build/$CI_COMMIT_REF_NAME/$CI_PROJECT_NAME/
    - cd /data/build/$CI_COMMIT_REF_NAME/$CI_PROJECT_NAME
    # - npm install
    - npm run preview
    - ls -a
